name: Automerge

on:
  pull_request:
  pull_request_target:

jobs:
  automerge-dependabot:
    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1.0.2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          allowed-author: "dependabot[bot]"
          merge-method: MERGE
  automerge-github-actions:
    name: Enable automerge on github-actions PRs
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on github-actions PRs
        uses: daneden/enable-automerge-action@v1.0.2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          allowed-author: "github-actions[bot]"
          merge-method: MERGE
  automerge:
    name: Enable automerge on owner PRs
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on owner PRs
        uses: daneden/enable-automerge-action@v1.0.2
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          allowed-author: "Razeen-Shaikh"
          merge-method: MERGE
